services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: "${DOCKER_USERNAME:-stylo}/stylo-backend:latest"
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: "${DOCKER_USERNAME:-stylo}/stylo-frontend:latest"
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
