version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: "${DOCKER_USERNAME}/stylo-backend:latest"
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/"]
      interval: 15s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE_URL: "http://backend:8000"
    image: "${DOCKER_USERNAME}/stylo-frontend:latest"
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
